hygieia/hygieia-scm-github-graphql-collector

pom.xml
=> increment version to 3.1.1-SNAPSHOT

src/main/java/com/capitalone/dashboard/collector/GitHubCollectorTask.java
Add delays when rate limit is reached, and when receiving 401 and 403.
Also fixed repo count.
=> Handle Github Rate Limit

pom.xml, src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java, src/test/java/com/capitalone/dashboard/collector/DefaultGitHubClientTest.java
=> Refactor: use the core code for REST client in order to get common logging

pom.xml
=> increment version to v3.1.2-SNAPSHOT

src/main/java/com/capitalone/dashboard/collector/GitHubCollectorTask.java
Catch unexpected exceptions to avoid premature termination of the loop (such as NullPointerException); fix the count to include skipped repositories; enhanced the log line to include status, lastUpdatedTime, commits/pr counts, etc
=> Catch unexpected exceptions to avoid premature termination of the loop

pom.xml, src/main/java/com/capitalone/dashboard/collector/GitHubCollectorTask.java
adapt review comments for the previous pull request;
also log pull request numbers
=> adapt review comments; log pull request numbers; update core version to pick up RestClient fix

pom.xml, src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java, src/main/java/com/capitalone/dashboard/collector/GitHubCollectorTask.java
=> Github collector sync data for enabled and pushed repos

src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java, src/main/java/com/capitalone/dashboard/collector/GitHubClient.java, src/main/java/com/capitalone/dashboard/collector/GitHubCollectorTask.java, src/test/java/com/capitalone/dashboard/collector/GitHubCollectorTaskTest.java
=> Handle GitHub rate limit by retrieving rate limit info from responses header &  sleep for [Retry-After] seconds when Abuse Rate Limit is hit.

src/main/java/com/capitalone/dashboard/collector/GitHubCollectorTask.java
=> fix LGTM warning.

src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java
reset the remaining rate lime to max allowed, when reset time is reached (more than 5 seconds in the past)
=> reset the remaining rate lime to max allowed, when reset time is reached

src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java
=> Always query all pull requests

src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java
=> Fix a bug where PRs are not saved in certain condition

pom.xml
=> Update hygieia core version

src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java
=> Fix exception when 0 PRs are collected

src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java
=> Improve performance

src/main/java/com/capitalone/dashboard/collector/GitHubCollectorTask.java
=> add logging for orphan commits

pom.xml
=> Update core version to 3.7.2

pom.xml, src/main/java/com/capitalone/dashboard/Application.java, src/main/java/com/capitalone/dashboard/controller/PingController.java
=> Ping github collector

pom.xml, src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java, src/main/java/com/capitalone/dashboard/model/MergeEvent.java
=> Change authorType from enum to string

pom.xml
- upgrade mongo driver
- Closes #42 #43 #44
=> update mongodb java library to 3.6.4 to support AWS DocumentDB

src/main/java/com/capitalone/dashboard/collector/GitHubCollectorTask.java
=> logging improvements, keep the milli second precision.

pom.xml, src/main/java/com/capitalone/dashboard/collector/GitHubCollectorTask.java
=> increment pom version, and change a variable name

pom.xml, src/main/java/com/capitalone/dashboard/collector/GitHubCollectorTask.java
=> update status message

pom.xml, src/main/java/com/capitalone/dashboard/collector/GitHubCollectorTask.java, src/main/java/com/capitalone/dashboard/model/GitHubRepo.java
- Github collector now supports Repository Classification (say SOURCE, BUILD, TEST or INFRA)
=> Add repository type to allOptions section of Github Collector.

pom.xml, src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java, src/main/java/com/capitalone/dashboard/collector/GitHubClient.java, src/main/java/com/capitalone/dashboard/collector/GitHubCollectorTask.java
- Added support for collector_item_metadata
- Added support for collection time in seconds
=> Enhancements for Metadata enrichment of collector_item

pom.xml, src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java, src/main/java/com/capitalone/dashboard/collector/GitHubClient.java, src/main/java/com/capitalone/dashboard/collector/GitHubCollectorTask.java
- Added more log statements
- Set the execution time in seconds
- Added support for upsertTime which can help with automatic data cleanup using mongo ttl-index
=> Added additional logging

pom.xml, src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java
=> Collect additions, deletions, and filesChangeds for GitRequest

pom.xml
=> Upgrade core version to 3.14.13

pom.xml, src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java, src/main/java/com/capitalone/dashboard/collector/GitHubSettings.java
=> Github collector : retry max 5 for error 

pom.xml, src/main/java/com/capitalone/dashboard/collector/GitHubCollectorTask.java
=> Cleanup github repos if they are deleted in Git Org

pom.xml, src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java
=> add changes to git commit type
